### ISSUE TITLE
Allow to configure the URL of Jenkins globally

### ISSUE THREAD

**Issue by kwin** [topicusfinan/bitbucket-webhooks-plugin#1]
Instead of configuring the URL of the according jenkins instance per hook/repository it should also be possible to set the globally. That URL should act as fallback in case no local Jenkins URL is set.

My use case is a Bitbucket Server instance containing roughly 100 repositories, all leveraging the same Jenkins instance.

**Comment by Eernie** [comment]
I'm integrating the Auto register webhooks voor the [BB branch source plugin](https://github.com/jenkinsci/bitbucket-branch-source-plugin) on jenkins. Maybe that will fix your configuration problems? That way all repos found will be auto registered.

**Comment by Andy2003** [comment]
Is there a timeline when auto-registration will work for jenkins?

in https://github.com/amuniz/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java#L294 there is currently nothing implemented. We have the same problem like @kwin that we got plenty of repositories within one Bitbucket projekt, that needs to get registered.
