### ISSUE TITLE
Unable to delete a webhook from UI

### ISSUE THREAD

**Issue by mkobit** [topicusfinan/bitbucket-webhooks-plugin#10]
Clicking `delete` doesn't seem to do anything with currently released plugin. I'm not sure if there is supposed to be a popup or anything, but nothing seems to happen.

<img width="294" alt="Delete button does not have the 'delete' command with it" src="https://cloud.githubusercontent.com/assets/1447148/19792230/f973b7b4-9c8d-11e6-81fb-92bb485f8230.png">

**Comment by Eernie** [comment]
This is a duplicate for #2. I'm waiting on the PR for the [Jenkins plugin](https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/21) to be merged. Then I'll release it.
