### ISSUE TITLE
Increase length of URLs

### ISSUE THREAD

**Issue by bbrouwer** [topicusfinan/bitbucket-webhooks-plugin#13]
I want to try to integrate this with Puppet Enterprise, but with authentication required, the URL needs to include a very long query parameter which makes the entire URL almost 1000 characters long. When I try to enter this URL, I get an error:
```
2016-11-16 09:31:30,457 ERROR [http-nio-7990-exec-14] @2YIT8Wx571x77982x0 1x53x61 10.240.8.228,10.226.18.246 "POST /mvc/error500 HTT
P/1.1" c.a.s.i.web.ErrorPageController There was an unhandled exception loading [/plugins/servlet/webhooks/repository/REL/release/se
ttings]
com.atlassian.activeobjects.internal.ActiveObjectsSqlException: There was a SQL exception thrown by the Active Objects library:
Database:
        - name:PostgreSQL
        - version:9.5.0.5
        - minor version:5
        - major version:9
Driver:
        - name:PostgreSQL Native Driver
        - version:PostgreSQL 9.4 JDBC4.2 (build 1202)

org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)
```

**Comment by Eernie** [comment]
Thanks for your feedback :+1: 

Yes I see the problem you're having.
We need to change the datatype to a text field I guess.

> Added @StringLength
> This annotation can be used to override the default maximum string length for String, URL, URI, and Enum fields.
> This is also the mechanism used to switch between VARCHAR and CLOB.
> examples:
> Not Annotated = VARCHAR(255)
> @StringLength(500) = VARCHAR(500)
> @StringLength(StringLength.UNLIMITED) = CLOB
> Note that you cannot set a specific maximum length that is greater than 767. That is the greatest length that is always allowed for VARCHARs in all the supported databases (specifically, this limit is from MySQL).

I'll change this in the near future.
