### ISSUE TITLE
Build not triggered

### ISSUE THREAD

**Issue by olbrichj** [topicusfinan/bitbucket-webhooks-plugin#15]
I'm trying to connect our Bitbucket Server Instance (4.6.1) with Jenkins (2.32.1).
The Cloudbees Multibranch Plugin is detecting the branches. I've created a webhook in Bitbucket with the target URL "<jenkins-address>/bitbucket-scmsource-hook/notify"

The multibranch Project as been added the way it is described at: https://go.cloudbees.com/docs/cloudbees-documentation/cje-user-guide/index.html#bitbucket

No build is being triggered after a push to an as Multibranch detected repository. 
Sadly I can't find some useful documentation.

How are you handling self signed https? I could imagine this to be a problem..

Any other suggestions?

**Comment by Eernie** [comment]
@olbrichj The plugin uses the provided client of Bitbucket. When the self signed cert is a problem then I'm afraid you have to dive in the documentation of Bitbucket about this. A quick Google gives me this : https://answers.atlassian.com/questions/29953294/can-bitbucket-webhooks-post-to-https-endpoints-that-use-a-self-signed-certificate I believe these webhooks use the same client as our plugin does.

Please reopen this issue when its not Self signed https related :)

**Comment by olbrichj** [comment]
Out of curiosity, the configuration above is correct?

**Comment by Eernie** [comment]
Sorry my bad, I totally overlooked the url part. You should also add the host of jenkins. something like: 
`https://youre-jenkins-machine.localdomain/jenkins/bitbucket-scmsource-hook/notify`

**Comment by olbrichj** [comment]
Thanks. Sadly this doesn't change anything. Do you have an example curl request I could use? I've tried using the push event described in the wiki, but I don't know what exactly to fill in:

Headers:
X-Event-Key:repo:push
X-Bitbucket-Type:<bitbucket server url>

Body:
{
    "repository": {
        "scmId": "git",
        "project": {
            "key": "REPOSITORY-NAME",
            "name": "REPOSITORY-NAME"
        },
        "slug": "topicus-force", 
        "public": false,
        "owner": {
            "username": "PROJECT-NAME",
            "displayName": "PROJECT-SHORTHAND"
        },
        "fullName": "PROJECT_1/topicus-force",
        "ownerName": "PROJECT_1"
    }
}

I don't know what to fill into "slug", "fullName" and "ownerName"

**Comment by Eernie** [comment]
Slug is the name of the repo but without special chars, so spaces will become dashes and all lowercase. 
Owner name is your Project key, you can see that in you're url as well `<bitbuckethost>/projects/<PROJECT_NAME>/repos`
FullName is a concatination of both.

**Comment by olbrichj** [comment]
Thanks a lot for your help. I'm kinda lost. Let's try it with an example:
jenkins: https://localhost/jenkins
PROJECT_NAME: APPS (per your description where to find in the url)
REPO_NAME: demo

then my request would look as this?

Headers:
X-Event-Key:repo:push
X-Bitbucket-Type: {bitbucket server url}

Body:
{
"repository": {
"scmId": "git",
"project": {
"key": "demo",
"name": "demo"
},
"slug": "demo",
"public": false,
"owner": {
"username": "APPS",
"displayName": "APPS"
},
"fullName": "APPS/demo",
"ownerName": "APPS"
}
}

**Comment by Eernie** [comment]
(Y)

**Comment by olbrichj** [comment]
even via postman I don't get it to execute :/ 
Thanks for all the help. I guess there are some configuration errors somewhere. Have to dig deeper

**Comment by olbrichj** [comment]
Hey,

for some reason I'm not able to reopen :/ But I'm also not sure if this is a bug in the plugin. Just asking, in case you've experienced something similar.

We got it working with a local instance on my laptop. Same BitBucket version and your plugin. Same structure as the BitBucket server we're using.
Self-Signed certs were at first a problem, but it was only due to the trust-store missing.

In the logs of our productive environment it mentions timeouts when executing the hook.
simple curl requests from that machine to our jenkins work fine.

Thanks again :)

**Comment by kuhnroyal** [comment]
I am getting something like this, dunno what to do.
```
"POST /scm/foo/bar.git/git-receive-pack HTTP/1.1" c.a.b.p.h.i.RequestFactoryWebHookProcessorWorker Invalid response from hook 'https://jenkins.example.com/bitbucket-scmsource-hook/notify', repository ID '123', status: '400' / 'Bad Request'
```

@olbrichj Use `X-Bitbucket-Type: server` with postman.

**Comment by olbrichj** [comment]
@kuhnroyal Thanks we figured that out :) I guess you are not using the Jenkins Cloudbees Plugin?

**Comment by kuhnroyal** [comment]
@olbrichj I am using the plugin, I can manually trigger builds with postman, not sure whats going on
