### ISSUE TITLE
Plugin ignores noProxyHosts

### ISSUE THREAD

**Issue by olbrichj** [topicusfinan/bitbucket-webhooks-plugin#16]
After quite some search we found a problem with the noProxyHosts list. We pass Bitbucket a list of noProxyHosts (in form of "*.company-name.com" which are internally used domains) and it can connect to our Jira instance.

When using the plugin, it is running into a timeout when trying to connect to our Jenkins. Deactivating this list results in the plugin being able to connect to the Jenkins, but Bitbucket needs this Proxy otherwise it cannot connect to the Marketspace (or anything else outside our internal network).

**Comment by Eernie** [comment]
I couldn't find anything about honoring the noProxyHosts, I was hoping this would all work out of the box by using the Httpclient that bitbucket provides. Apparently this isn't true. 

Do you have any knowledge about how to honor the noProxyHosts list?

**Comment by KamikaZeeFu** [comment]
I checked https://github.com/Nerdwin15/stash-jenkins-postreceive-webhook (since that plugin works with nonProxyHosts) and they don't rely on the standard http client, and instead use a custom apache httpClient.

I'll prepare a PR adding the required configuration.

**Comment by KamikaZeeFu** [comment]
I created two separate PRs, #20 and #21, which both fix the issue at hand.
One still uses the atlassian httpClient, the other one swaps it out for an apache httpClient.

**Comment by KamikaZeeFu** [comment]
The atlassian PR issued by me unfortunately didn't fix the bug, so this has to be re-opened :(
