### ISSUE TITLE
Triggering Jenkins BitBucket Project twice

### ISSUE THREAD

**Issue by luka5z** [topicusfinan/bitbucket-webhooks-plugin#28]
When making `git push` combining multiple commits, I've noticed:
- Particular Jenkins BitBucket Project to be triggered twice
- Http server logs two request from BitBucket:
```
10.21.200.141 - - [15/Mar/2017:14:48:32 +0100] "POST /jenkins/bitbucket-scmsource-hook/notify HTTP/1.1" 200 550 "-" "Atlassian HttpClient 0.23.0 / Bitbucket-4.5.2 (4005002) / Default"
10.21.200.141 - - [15/Mar/2017:14:48:33 +0100] "POST /jenkins/bitbucket-scmsource-hook/notify HTTP/1.1" 200 373 "-" "Atlassian HttpClient 0.23.0 / Bitbucket-4.5.2 (4005002) / Default"
```
Does this plug-ins make multiple calls? Or should I look for problem somewhere else?

**Comment by Eernie** [comment]
Dit you push to multiple branches, or did you maybe have a PR open for that branch?

**Comment by luka5z** [comment]
I'm pushing two commits with a single push command to targeting one branch.

I'm using `mvn release:prepare`. Afterwards in Jenkins I'm seeing two builds being triggered in a matter of few seconds. The former build contains two commits and and latter is just an "empty" re-build.

**Comment by Eernie** [comment]
I'm guessing this PR will fix that for you https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/37

**Comment by luka5z** [comment]
Thanks, I will definitely check that. Does it mean I need to upgrade all my plugins to support SCM API 2.0?
