### ISSUE TITLE
api to fill in trigger details programmatically

### ISSUE THREAD

**Issue by madhukiranbr** [topicusfinan/bitbucket-webhooks-plugin#29]
Hi,

I see a few paths defined in api package nl.topicus.bitbucket.api; However I don't see any documentation.
Please explain if an api exists. 

I tried to access configuration without luck
o/p:
`<status>`
`<status-code>404</status-code>`
`<message>`
`null for uri: http://{host}/rest/api/1.0/projects/{projectkey}/repos/{repo}/configurations`
`</message>`
`</status>`

Thanks

**Comment by Eernie** [comment]
I believe the url  `http://{host}/rest/webhook/1.0/projects/{projectkey}/repos/{repo}/configurations`.

The `/api/` url is only for core api's

**Comment by madhukiranbr** [comment]
Thanks Eernie. That works

**Comment by JananiJM** [comment]
@Eernie  is there a separate url for setting pull request and push events in configurations ?
