### ISSUE TITLE
Support for Bitbucket Data Center

### ISSUE THREAD

**Issue by markottaviani** [topicusfinan/bitbucket-webhooks-plugin#3]
We're be interested in using this plugin for our Bitbucket Data Center instance [once this PR gets completed.](https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/5)

Can you make sure this plugin is Bitbucket Data Center compatible and mark it as such in the Atlassian Marketplace?

https://developer.atlassian.com/bitbucket/server/docs/latest/how-tos/cluster-safe-plugins.html

Thanks!

**Comment by Eernie** [comment]
I'll look in to that. First i'm awaiting the Other PR to be merged. But I'm starting to think that will take a while. 

Looking to the link you've provides, this should be an issue. Events are only sent on one node in the cluster, so be default this plugin is Cluster Safe and also data center compatible.
