### ISSUE TITLE
Bitbucket 5.0 support

### ISSUE THREAD

**Issue by kuhnroyal** [topicusfinan/bitbucket-webhooks-plugin#44]
Just released - maybe the plugin only has to be marked compatible in the marketplace.

**Comment by kuhnroyal** [comment]
It compiles against the 5.0.0 API, so it should be compatible.

**Comment by Eernie** [comment]
I'm currently on vacation, so I'm not able to test it. If you can compile and test it that would be awesome. Otherwise I'll get back to it in a couple of weeks.

**Comment by kuhnroyal** [comment]
The current plugin version works as far as I can tell, it only needs to be marked compatible in the Atlassian-marketplace.

**Comment by Eernie** [comment]
:+1:
