### ISSUE TITLE
How to configure Bitbucket Server <> Jenkins ?

### ISSUE THREAD

**Issue by donnib** [topicusfinan/bitbucket-webhooks-plugin#6]
Hi,
I am trying to get the link between Bitbucket Server 4.8.0 <> Jenkins by using Bitbucket Branch Source Plugin v. 1.8 and as far as i can see from the release log (http://bit.ly/2dbXIyB) the support for Webhooks for Bitbucket Server is in now in but it doesn't work, yes i did install the plugin you made http://bit.ly/2dpnqgS that is required. Not sure where to ask for help on this. The help here from the Bitbucket Branch Source Plugin states there is no support for Bitbucket Server (http://bit.ly/2dikwcm) but i am guessing this is just outdated since it's stated that 1.8 supports server version.

Any ideas what i need to configure ? Do i need to add something myself in the Webhooks in Bitbucket Server if so what and what about in Jenkins ?

/donnib

**Comment by Eernie** [comment]
Yes you need to configure the 'branch-source-plugin' url in bit bucket, You can do this by going to the repo in bitbucket > settings > webhooks. There you can add a hook to your Jenkins machine.
The url to use can be found in you jenkins machine. In the configuration panel of a job you can select the option "auto-register", when you press the `?` sign behind it, you'll get an explanation about how to do this manually. There you'll find something like: `http://<jenkins-host>/bitbucket-scmsource-hook/notify`. I'm not sure though.

**Comment by donnib** [comment]
@Eernie thx for your answer. So i tried your suggestion but still it doesn't work. :(

![image 2](https://cloud.githubusercontent.com/assets/252702/18985051/47aa8546-86f6-11e6-9a71-1c16cfb44235.png)
![image 1](https://cloud.githubusercontent.com/assets/252702/18985050/47aaa15c-86f6-11e6-86bb-e3c480baaf51.png)
![image 3](https://cloud.githubusercontent.com/assets/252702/18985089/73de6ed4-86f6-11e6-901a-7a2c950263fe.png)

Any ideas what i might be doing wrong would be appreciated ;)

**Comment by donnib** [comment]
So i solved my problem now. The problem was purely in casing, i found out only when i enabled a logger for "com.cloudbees.jenkins.plugins.bitbucket" then i could see it could not find the multibranch project and that lead me to the name of the repository (casing). Works great now. Thx
