### ISSUE TITLE
Not available via the 'hooks' API

### ISSUE THREAD

**Issue by mkobit** [topicusfinan/bitbucket-webhooks-plugin#9]
I was building automation for the Bitbucket hooks for a repository, and found out it wasn't shown in the Hooks API (https://developer.atlassian.com/static/rest/bitbucket-server/4.10.1/bitbucket-rest.html#idp720528). 

Is there a different API to go through to configure this webhook?

**Comment by Eernie** [comment]
Yes there is a different api for the webhooks. 
This is a feature of the new release.

**Comment by esmaras** [comment]
@mkobit Here is some documentation on Jenkins that details how to use the REST API as well: https://support.cloudbees.com/hc/en-us/articles/115000083932?input_string=multibranch+pipelines+set+post+webhooks+in+bitbucket
